INSERT INTO `catagory` (`c_name`) VALUES
('Action'),
('Adventure'),
('Fantasy'),
('Science Fiction'),
('Mystery'),
('Horror'),
('Romance'),
('Drama'),
('Slice of Life'),
('Comedy'),
('Sports'),
('Supernatural'),
('Mecha'),
('Psychological'),
('Thriller'),
('Historical'),
('Magic'),
('School'),
('Military'),
('Space'),
('Super Power'),
('Music'),
('Parody'),
('Game'),
('Martial Arts'),
('Police'),
('Demons'),
('Mature'),
('Martial Arts'),
('Kids'),
('Seinen'),
('Shoujo'),
('Shounen'),
('Josei'),
('Harem'),
('Isekai'),
('Tragedy'),
('Ecchi'),
('Superhero'),
('Vampire'),
('Samurai'),
('Historical'),
('Cyberpunk'),
('Dystopian'),
('Post-Apocalyptic'),
('Gender Bender'),
('Space Opera'),
('Time Travel'),
('Aliens'),
('Art'),
('Cooking'),
('Hentai'),
('LGBTQ+'),
('Philosophical'),
('Political'),
('Conspiracy'),
('Espionage'),
('Gothic'),
('Military Science'),
('Mythology'),
('Occult'),
('Religious'),
('Social Issues'),
('Surreal'),
('Wuxia'),
('Yaoi'),
('Yuri'),
('Biography'),
('Autobiography'),
('Business'),
('Dementia'),
('Doujinshi'),
('Genderswap'),
('Ghost'),
('Isekai'),
('Psychological'),
('Reincarnation'),
('Reverse Harem'),
('Shotacon'),
('Shoujo Ai'),
('Shounen Ai'),
('Silent Manga'),
('Smut'),
('Web Comic'),
('Webtoon');